/*
 * File: app/view/PrincipalViewport.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtJS.view.PrincipalViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.main',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    title: 'Productos',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Nombre'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'number',
                            text: 'Precio'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'Fecha Publicación'
                        }
                    ],
                    listeners: {
                        boxready: {
                            fn: me.onGridpanelBoxReady,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'form',
                    region: 'west',
                    width: 282,
                    bodyPadding: 10,
                    title: 'Filtros',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Buscar',
                            emptyText: 'Ingrese Fecha, Precio, Nombre'
                        },
                        {
                            xtype: 'button',
                            text: 'Buscar'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridpanelBoxReady: function(component, width, height, eOpts) {
            var store = Ext.data.StoreManager.lookup("ProductoStore");
            store.add({
                nombre: 'Portatil',
                precio: 2000000,
                id: 1
            });
    }

});